"""empty message

Revision ID: 292600a530f9
Revises: 64b847dceff0
Create Date: 2017-04-25 20:11:50.298245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292600a530f9'
down_revision = '64b847dceff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
